# This playbook takes care of the base things,
# like bash, vim, and git
---
- name: Base setup
  hosts: localhost
  roles:
    - ohmyzsh
    - dotfiles
    - vim
    - git
    - composer
    - mactweeks
    - terminal
