---
- name: Install useful desktop tools (brew)
  homebrew: name={{ item }} state=present
  with_items: "{{ desktop.tools }}"
  when: ansible_pkg_mgr == "homebrew"
  tags:
    - packages
    - network
    - tools

- name: Install brew cask tap (brew)
  homebrew_tap: name="caskroom/cask" state=present
  when: ansible_pkg_mgr == "homebrew"
  tags:
    - applications

- name: Install python tools
  pip: name={{ item }} state=present
  with_items: "{{ desktop.pythonTools }}"
  tags:
    - packages
    - network
    - tools
    - pip

- name: Install useful desktop applications (brew cask)
  homebrew_cask: name={{ item }} state=present
  with_items: "{{ desktop.applications }}"
  when: ansible_pkg_mgr == "homebrew"
  tags:
    - applications

- name: Ensure MAS is installed
  homebrew: name=mas state=present
  tags:
    - applications
    - mas

- name: Get MAS account status
  shell: 'mas account'
  register: mas_account_result
  failed_when: mas_account_result.rc > 1
  changed_when: false
  tags:
    - applications
    - mas

- name: List installed MAS apps.
  command: mas list
  register: mas_list
  check_mode: no
  changed_when: false
  tags:
    - applications
    - mas

- name: Ensure configured MAS apps are installed.
  command: mas install "{{ item.id|default(item) }}"
  with_items: "{{ desktop.appstore }}"
  when: "'{{ item.id|default(item) }}' not in mas_list.stdout"
  tags:
    - applications
    - mas

- name: Upgrade all apps (if configured).
  command: mas upgrade
  when: desktop.mas_upgrade_all_apps
  tags:
    - applications
    - mas

- name: Install user image from Gravatar
  get_url: url=https://s.gravatar.com/avatar/e1fd1e9cd946dfd693ad83cdaa79b723?s=100 dest=~/.face
