---
- name: Install useful desktop tools (brew)
  homebrew: name={{ item }} state=present
  with_items: "{{ desktop.tools }}"
  when: ansible_pkg_mgr == "homebrew"
  tags:
    - packages
    - network
    - tools

- name: Install brew cask tap (brew)
  homebrew_tap: name="caskroom/cask" state=present
  when: ansible_pkg_mgr == "homebrew"
  tags:
    - applications

- name: Install python tools
  pip: name={{ item }} state=present
  with_items: "{{ desktop.pythonTools }}"
  when: ansible_pkg_mgr == "pip"
  tags:
    - packages
    - network
    - tools
    - pip

- name: Install useful desktop applications (brew cask)
  homebrew_cask: name={{ item }} state=present
  with_items: "{{ desktop.applications }}"
  when: ansible_pkg_mgr == "homebrew"
  tags:
    - applications

- name: Install user image from Gravatar
  get_url: url=https://s.gravatar.com/avatar/e1fd1e9cd946dfd693ad83cdaa79b723?s=100 dest=~/.face
