- name: Install useful desktop tools (dnf)
  become: yes
  dnf: name={{ item }} state=present
  with_items: "{{ desktop.linuxTools }}"
  when: ansible_pkg_mgr == "dnf"
  tags:
    - packages
    - network

- name: Install useful desktop tools (yum)
  become: yes
  yum: name={{ item }} state=present
  with_items: "{{ desktop.linuxTools }}"
  when: ansible_pkg_mgr == "yum"
  tags:
    - packages
    - network

- name: Install useful desktop tools (brew)
  homebrew: name={{ item }} state=present
  with_items: "{{ desktop.brewTools }}"
  when: ansible_pkg_mgr == "homebrew"
  tags:
    - packages
    - network

- name: Install brew cask tap (brew)
  homebrew_tap: name="caskroom/cask" state=present
  when: ansible_pkg_mgr == "homebrew"
  tags:
    - packages

- name: Install useful desktop applications (brew cask)
  homebrew_cask: name={{ item }} state=present
  with_items: "{{ desktop.brewApplications }}"
  when: ansible_pkg_mgr == "homebrew"
  tags:
    - packages

- name: Install user image from Gravatar
  get_url: url=https://s.gravatar.com/avatar/e1fd1e9cd946dfd693ad83cdaa79b723?s=100 dest=~/.face
