---
- name: Copy dotfiles
  copy: src={{ item }} dest={{ ansible_user_dir }}/.{{ item | basename }}
  with_fileglob:
    - ./dotfiles/*
  tags:
    - files

- name: Ensure bin/ folder exists
  file: path={{ ansible_user_dir}}/bin state=directory
  tags:
    - files

- name: Ensure ~/work folder exists
  file: path={{ ansible_user_dir}}/work state=directory
  tags:
    - files

- name: Ensure ~/code folder exists
  file: path={{ ansible_user_dir}}/code state=directory

- name: Copy bin/ files
  copy: src={{ item }} dest={{ ansible_user_dir }}/bin/{{ item | basename }} mode=ug+rwx,o+rx
  with_fileglob:
    - ./bin/*
  tags:
    - files

- name: Install useful tools (brew)
  homebrew: name={{ item }} state=present
  with_items: "{{ dotfiles.dependencies }}"
  when: ansible_pkg_mgr == "homebrew"
  tags:
    - packages
    - network

