desktop:
  tools:
    - coreutils
    - csshx
    - fabric
    - gd
    - goaccess
    - htop-osx
    - percona-toolkit
    - pssh
    - pwgen
    - python
    - python3
    - pyenv
    - rbenv
    - rbenv-default-gems
    - ruby
    - socat
    - tor
    - tree
    - watch
    - gpg
    - kubernetes-cli
    - asciinema
    - mas
    - nikto
    - sqlmap
    - hydra
    - wpscan
  pythonTools:
    - glances
  applications:
    - 1password
    - aerial
    - alfred
    - visual-studio-code
    - bartender
    - docker
    - dropbox
    - flexiglass
    - wavebox
    - google-chrome
    - iterm2
    - sequel-pro
    - skype
    - slack
    - spotify
    - the-unarchiver
    - vagrant
    - vagrant-manager
    - viber
    - istat-menus
    - ssh-tunnel-manager
    - wireshark
    - owasp-zap
  mas_upgrade_all_apps: 0
  appstore:
    - { id: 426410278, name: "Flexiglass" }
    - { id: 587769990, name: "EyeFriendly" }
    - { id: 425424353, name: "The Unarchiver" }
    - { id: 475260933, name: "HardwareGrowler" }
    - { id: 866773894, name: "Quiver" }
    - { id: 638161122, name: "YubiKey Personalization Tool" }
    - { id: 715768417, name: "Microsoft Remote Desktop" }
    - { id: 924726344, name: "Deliveries" }
    - { id: 430255202, name: "Mactracker" }
    - { id: 865500966, name: "feedly" }
