desktop:
  linuxTools:
    - terminattor
  brewTools:
    - selecta
    - socat
    - tmux-cssh
    - tree
    - watch
    - goaccess
    - csshx
    - htop-osx
    - percona-toolkit
    - python
    - python3
    - rbenv
    - rbenv-default-gems
    - ruby
  brewApplications:
    - atom
    - google-chrome

