desktop:
  tools:
    - coreutils
    - csshx
    - fabric
    - gd
    - goaccess
    - groovy
    - htop-osx
    - percona-toolkit
    - pssh
    - pwgen
    - python
    - python3
    - rbenv
    - rbenv-default-gems
    - ruby
    - selecta
    - socat
    - tmux-cssh
    - tor
    - tree
    - watch
  applications:
    - 1password
    - aerial
    - alfred
    - atom
    - bartender
    - brackets
    - cord
    - docker
    - dropbox
    - flexiglass
    - franz
    - google-chrome
    - iterm2
    - sequel-pro
    - skype
    - slack
    - spotify
    - the-unarchiver
    - vagrant
    - vagrant-manager
    - viber

