---
- name: Installing Zsh and git dependencies (brew)
  homebrew: name={{ item }} state=present
  with_items: "{{ ohmyzsh.dependenciesBrew }}"
  when: ansible_pkg_mgr == "homebrew"
  tags:
    - packages
    - terminal

- name: Backing up existing ~/.zshrc
  copy: src={{ ansible_user_dir }}/.zshrc dest={{ ansible_user_dir }}/.zshrc.orig
  tags:
    - files

- name: Cloning oh-my-zsh
  git:
    repo=https://github.com/robbyrussell/oh-my-zsh
    dest={{ ansible_user_dir }}/.oh-my-zsh
  tags:
    - cloning

- name: Chanching default shell to zsh
  shell: chsh -s $(grep /zsh$ /etc/shells | tail -1)
  tags:
    - terminal

- name: Clone zsh autosuggestions
  git:
    repo=https://github.com/zsh-users/zsh-autosuggestions
    dest={{ ansible_user_dir }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions
  tags:
    - terminal
    - plugins

- name: Ensure custom themes folder exists
  file: path={{ ansible_user_dir }}/.oh-my-zsh/custom/themes mode=0755 state=directory
  tags:
    - terminal
    - themes

- name: Ensute powerlevel9k theme folder exists
  file: path={{ ansible_user_dir }}/.oh-my-zsh/custom/themes/powerlevel9k mode=0755 state=directory
  tags:
    - terminal
    - themes

- name: Clone prowerlevel9k theme
  git:
    repo=https://github.com/bhilburn/powerlevel9k.git
    dest={{ ansible_user_dir }}/.oh-my-zsh/custom/themes/powerlevel9k
  tags:
    - terminal
    - themes
