dotfiles:
  dependenciesBrew:
    - bash-completion
    - ack
    - links
    - tmux
    - tmux-cssh
    - rlwrap
    - reattach-to-user-namespace --wrap-pbcopy-and-pbpaste  
  dependenciesGem:
    - i2cssh
