---
- name: Install git and tools (dnf)
  sudo: yes
  dnf: name={{ item }} state=present
  with_items: "{{ git.dependencies }}"
  when: ansible_pkg_mgr == "dnf"
  tags:
    - packages
    - network

- name: Install git and tools (yum)
  sudo: yes
  yum: name={{ item }} state=present
  with_items: "{{ git.dependencies }}"
  when: ansible_pkg_mgr == "yum"
  tags:
    - packages
    - network

- name: Copy dotfiles
  copy: src={{ item }} dest={{ ansible_user_dir }}/.{{ item | basename }}
  with_fileglob:
    - ./dotfiles/*
  tags:
    - files

- name: Create .gitconfig file
  template:  src=gitconfig.j2 dest={{ ansible_user_dir}}/.gitconfig
  tags:
    - files
