---
- name: Install java using brew cask
  homebrew: name="openjdk" state=present
  when: ansible_pkg_mgr == "homebrew"
  tags:
    - packages
    - network

- name: Install gradle and maven (brew)
  homebrew: name={{ item }} state=present
  with_items: "{{ java.dependencies }}"
  when: ansible_pkg_mgr == "homebrew"
  tags:
    - packages
    - network
