vim:
  folders:
    - .vim
    - .vim/autoload
    - .vim/bundle
    - .vim/colors
    - .vim/ftdetect
    - .vim/ftplugin
    - .vim/indent
    - .vim/plugin
    - .vim/ruby
    - .vim/syntax
    - .vim/ruby/vim
    - .vim/sessions
    - .vim/undodir
  dependencies:
    - selecta
    - neovim
  vundle:
    - { name: "Vundle.vim", repo: "https://github.com/VundleVim/Vundle.vim.git" }
  vimPlugins:
    - { name: "tpope/vim-fugitive", description: "Git wrapper", active: true }
    - { name: "airblade/vim-gitgutter", description: "Shows a git diff in the gutter", active: true }
    - { name: "mhinz/vim-signify", description: "Show a diff using Vim its sign column", active: true }
    - { name: "chriskempson/base16-vim", description: "Syntax highlighting for hackers", active: true }
    - { name: "ctrlpvim/ctrlp.vim", description: "Full path fuzzy file, buffer, mru, tag.. finder", active: true }
    - { name: "docunext/closetag.vim", description: "Functions and mappings to close open HTML/XML tags", active: true }
    - { name: "duff/vim-scratch", description: "Create a temporary scratch buffer", active: true }
    - { name: "editorconfig/editorconfig-vim", description: "EditorConfig plugin", active: true }
    - { name: "ervandew/supertab", description: "Perform all your vim insert mode completions with Tab", active: true }
    - { name: "flazz/vim-colorschemes", description: "one colorscheme pack to rule them all", active: true }
    - { name: "gko/vim-coloresque", description: "css/less/sass/html color preview", active: true }
    - { name: "gregsexton/gitv", description: "gitv is a repository viewer similar to gitk", active: true }
    - { name: "majutsushi/tagbar", description: "Vim plugin that displays tags in a window, ordered by scope", active: true }
    - { name: "mattn/gist-vim", description: "This is a vimscript for creating gists", active: true }
    - { name: "mattn/webapi-vim", description: "vim interface to Web API", active: true }
    - { name: "mileszs/ack.vim", description: "Vim plugin for the Perl module / CLI script 'ack'", active: true }
    - { name: "scrooloose/nerdcommenter", description: "Vim plugin for intensely orgasmic commenting", active: true }
    - { name: "scrooloose/nerdtree", description: "A tree explorer plugin for vim.", active: true }
    - { name: "vim-syntastic/syntastic", description: "Syntax checking hacks for vim", active: true }
    - { name: "sheerun/vim-polyglot", description: "A solid language pack for Vim.", active: true }
    - { name: "tmhedberg/matchit", description: "extended % matching for HTML, LaTeX, and many other languages", active: true }
    - { name: "tpope/vim-unimpaired", description: "unimpaired.vim: pairs of handy bracket mappings", active: true }
    - { name: "vim-airline/vim-airline", description: "lean & mean status/tabline for vim that's light as air", active: true }
    - { name: "vim-airline/vim-airline-themes", description: "A collection of themes for vim-airline", active: true }
    - { name: "vim-php/tagbar-phpctags.vim", description: "Using phpctags to generate php ctags index for vim plugin tagbar", active: true }
    - { name: "vim-scripts/CSApprox", description: "Make gvim-only colorschemes work transparently in terminal vim", active: true }
    - { name: "vim-scripts/jQuery", description: "Syntax file for jQuery", active: true }
    - { name: "vim-scripts/PDV--phpDocumentor-for-Vim", description: "Provides really comfortable generation of phpDocumentor doc blocks for PHP4 & 5", active: true }
    - { name: "vim-scripts/SearchComplete", description: "Tab completion of words inside of a search ('/')", active: true }
    - { name: "vim-scripts/Smart-Tabs", description: "Use tabs for indent, spaces for alignment ", active: false }
    - { name: "vim-scripts/ZoomWin", description: "Zoom in/out of windows (toggle between one window and multi-window)", active: true }
    - { name: "Xuyuanp/nerdtree-git-plugin", description: "A plugin of NERDTree showing git status", active: true }
    - { name: "joonty/vim-phpqa", description: "PHP QA tools for vim", active: true }
