vim:
  folders:
    - .vim
    - .vim/autoload
    - .vim/bundle
    - .vim/colors
    - .vim/ftdetect
    - .vim/ftplugin
    - .vim/indent
    - .vim/plugin
    - .vim/ruby
    - .vim/syntax
    - .vim/ruby/vim
    - .vim/sessions
    - .vim/undodir
  dependencies:
  plugins:
    - https://github.com/airblade/vim-gitgutter.git
    - https://github.com/chriskempson/base16-vim.git
    - https://github.com/ctrlpvim/ctrlp.vim
    - https://github.com/docunext/closetag.vim.git
    - https://github.com/duff/vim-scratch.git
    - https://github.com/editorconfig/editorconfig-vim.git
    - https://github.com/ervandew/supertab.git
    - https://github.com/flazz/vim-colorschemes.git
    - https://github.com/gko/vim-coloresque.git
    - https://github.com/gregsexton/gitv.git
    - https://github.com/majutsushi/tagbar.git
    - https://github.com/mattn/gist-vim.git
    - https://github.com/mattn/webapi-vim.git
    - https://github.com/mileszs/ack.vim.git
    - https://github.com/scrooloose/nerdcommenter.git
    - https://github.com/scrooloose/nerdtree.git
    - https://github.com/scrooloose/syntastic.git
    - https://github.com/sheerun/vim-polyglot.git
    - https://github.com/tmhedberg/matchit.git
    - https://github.com/tpope/vim-fugitive.git
    - https://github.com/tpope/vim-unimpaired.git
    - https://github.com/vim-airline/vim-airline.git
    - https://github.com/vim-airline/vim-airline-themes.git
    - https://github.com/vim-php/tagbar-phpctags.vim.git
    - https://github.com/vim-scripts/CSApprox.git
    - https://github.com/vim-scripts/jQuery.git
    - https://github.com/vim-scripts/PDV--phpDocumentor-for-Vim.git
    - https://github.com/vim-scripts/SearchComplete.git
    - https://github.com/vim-scripts/Smart-Tabs.git
    - https://github.com/vim-scripts/ZoomWin.git
    - https://github.com/Xuyuanp/nerdtree-git-plugin.git
