---
- name: Change dock autohide timer to 0
  command: defaults write com.apple.dock autohide-time-modifier -int 0
  tags:
    - tweeks

- name: Change dock autohide to true
  command: defaults write com.apple.dock autohide -int 1
  tags:
    - tweeks

- name: Change dock possition to left
  command: defaults write com.apple.dock orientation -string left
  tags:
    - tweeks

- name: Change dock show recents to false
  command: defaults write com.apple.dock show-recents -int 0
  tags:
    - tweeks

- name: Change dock tilesize to 50
  command: defaults write com.apple.dock tilesize -int 50
  tags:
    - tweeks

- name: Enable screensaver
  command: defaults write com.apple.screensaver askForPassword -int 1
  tags:
    - tweeks

- name: Remove screensaver token
  command: defaults write com.apple.screensaver tokenRemovalAction -int 0
  tags:
    - tweeks

- name: Change screensaver ask for password delay
  command: defaults write com.apple.screensaver askForPasswordDelay -float 0.0
  tags:
    - tweeks

- name: Enable automatic updates
  command: defaults write /Library/Preferences/com.apple.SoftwareUpdate AutomaticCheckEnabled -int 1
  become: true
  tags:
    - tweeks

- name: Enable security updates
  command: defaults write /Library/Preferences/com.apple.SoftwareUpdate ConfigDataInstall -bool true
  become: true
  tags:
    - tweeks

- name: Enable critical updates
  command: defaults write /Library/Preferences/com.apple.SoftwareUpdate CriticalUpdateInstall -bool true
  become: true
  tags:
    - tweeks

- name: Restart dock
  command: killall Dock
  tags:
    - tweeks
