---
- name: Ensure .vim/ folder structure exists
  file: path={{ ansible_user_dir}}/{{ item }} state=directory
  with_items: "{{ vim.folders }}"
  tags:
    - files

- name: Install vim plugin dependencies (brew)
  homebrew: name={{ item }} state=present
  with_items: "{{ vim.dependencies }}"
  when: ansible_pkg_mgr == "homebrew"
  tags:
   - packages
   - network

- name: Install vim vundle
  git: repo={{ item.repo }} dest={{ ansible_user_dir }}/.vim/bundle/{{ item.name }}
  with_items: "{{ vim.vundle }}"
  register: vundle_installed
  tags:
    - network
    - files
    - vundle

- name: Copy vimrc with plugins using vundle
  template: src="vimrc-vundle.j2" dest="{{ ansible_user_dir }}/.vimrc"
  tags:
    - files
    - vimrc

- name: Run vundle plugin install
  shell: vim +PluginInstall +qall
  register: vim_plugins_installed
  tags:
    - vim-plugins
    - vim-plugins-install

# - name: Run vundle plugin clean
#   shell: vim +PluginClean +qall
#   register: vim_plugins_cleaned
#   tags:
#     - vim-plugins
#     - vim-plugins-clean
